# Generated by Django 4.2.7 on 2023-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("avatar1.png", "Goat"),
                    ("avatar2.png", "Fish"),
                    ("avatar3.png", "Shark"),
                ],
                default="avatar1.png",
                max_length=100,
            ),
        ),
    ]
