# Generated by Django 4.2.7 on 2024-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0002_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.CharField(max_length=25)),
                ("aiButton", models.BooleanField()),
                ("result", models.IntegerField(default=0)),
                ("aiIterations", models.IntegerField(default=0)),
                ("aiCards", models.CharField(max_length=10)),
                ("playerCards", models.CharField(max_length=10)),
                ("communityCards", models.CharField(max_length=50)),
            ],
        ),
    ]
