# Generated by Django 4.2.7 on 2024-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0003_poker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poker",
            name="aiCards",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="poker",
            name="communityCards",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="poker",
            name="history",
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name="poker",
            name="playerCards",
            field=models.CharField(max_length=100),
        ),
    ]
