# Generated by Django 4.2.7 on 2024-02-14 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shortdeck", "0004_alter_poker_aicards_alter_poker_communitycards_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hands_played", models.IntegerField(default=0)),
                ("vpip", models.FloatField(default=0.0)),
                ("pfr", models.FloatField(default=0.0)),
                ("three_bet_percentage", models.FloatField(default=0.0)),
                ("aggression_factor", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_statistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("stage", models.CharField(max_length=255)),
                ("is_voluntary", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
