# Generated by Django 4.2.7 on 2024-02-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0007_handsplayed_ai_cards_handsplayed_community_cards_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="hands_played",
        ),
        migrations.AddField(
            model_name="handsplayed",
            name="game",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hands_played",
                to="shortdeck.game",
            ),
            preserve_default=False,
        ),
    ]
