# Generated by Django 4.2.7 on 2024-02-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0009_alter_handsplayed_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handsplayed",
            name="game",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hands_played",
                to="shortdeck.game",
            ),
            preserve_default=False,
        ),
    ]
