# Generated by Django 4.2.7 on 2024-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0010_alter_handsplayed_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="handsplayed",
            name="won",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="handsplayed",
            name="community_cards",
            field=models.CharField(max_length=1000),
        ),
    ]
