# Generated by Django 4.2.7 on 2024-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0012_handsplayed_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameaction",
            name="ai_action",
            field=models.BooleanField(default=False),
        ),
    ]
