# Generated by Django 4.2.7 on 2024-02-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0013_gameaction_ai_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_set_key", models.TextField()),
                ("strategy", models.JSONField()),
                ("action_taken", models.CharField(max_length=10)),
                ("probabilities", models.JSONField()),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortdeck.handsplayed",
                    ),
                ),
            ],
        ),
    ]
