# Generated by Django 4.2.7 on 2024-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0014_decisiondata"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisiondata",
            name="bucket_value",
            field=models.IntegerField(default=0),
        ),
    ]
