# Generated by Django 4.2.7 on 2024-02-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0015_decisiondata_bucket_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisiondata",
            name="hand",
        ),
        migrations.AddField(
            model_name="decisiondata",
            name="game_action",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decision_data",
                to="shortdeck.gameaction",
            ),
            preserve_default=False,
        ),
    ]
