# Generated by Django 4.2.7 on 2024-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0016_remove_decisiondata_hand_decisiondata_game_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decisiondata",
            name="bucket_value",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
