# Generated by Django 4.2.7 on 2024-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0017_alter_decisiondata_bucket_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cards", models.CharField(max_length=255, unique=True)),
                ("bucket_value", models.IntegerField()),
                ("hand_strength", models.IntegerField()),
            ],
        ),
    ]
