# Generated by Django 4.2.7 on 2024-02-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0018_handstrength"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisiondata",
            name="player_hand",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
