# Generated by Django 4.2.7 on 2024-02-28 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shortdeck", "0020_userprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="handsplayed",
            name="big_blind",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handsplayed",
            name="big_blind_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="big_blind_hands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="handsplayed",
            name="small_blind",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="handsplayed",
            name="small_blind_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="small_blind_hands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("avatar1.png", "Goat"),
                    ("avatar2.png", "cheetah"),
                    ("avatar3.png", "Shark"),
                    ("avatar4.png", "raccoon"),
                    ("avatar5.png", "panda"),
                    ("avatar6.png", "fox"),
                    ("avatar7.png", "owl"),
                    ("avatar8.png", "kitten"),
                    ("avatar9.png", "monkey"),
                    ("avatar10.png", "moose"),
                ],
                default="avatar1.png",
                max_length=100,
            ),
        ),
    ]
