# Generated by Django 4.2.7 on 2024-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0021_handsplayed_big_blind_handsplayed_big_blind_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handsplayed",
            name="big_blind_user",
        ),
        migrations.RemoveField(
            model_name="handsplayed",
            name="small_blind_user",
        ),
        migrations.AddField(
            model_name="handsplayed",
            name="is_user_big_blind",
            field=models.BooleanField(default=False),
        ),
    ]
