# Generated by Django 4.2.7 on 2024-03-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0023_remove_decisiondata_bucket_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decisiondata",
            old_name="bucket_values",
            new_name="bucket_value",
        ),
    ]
