# Generated by Django 4.2.7 on 2024-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortdeck", "0024_rename_bucket_values_decisiondata_bucket_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decisiondata",
            name="bucket_value",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
